#33 Added Death Functionality
Usmo/2D-Runner pull request #66
Opened 2022-10-30 16:44 UTC by VeikkaH

Added death functionality, death screen and tests.

2022-11-01 13:19 UTC, Usmo commented on Assets/Scripts/DeathScreen.cs
> +        } */
This commented section is not needed

2022-11-01 13:22 UTC, Usmo commented on Assets/Scripts/Player.cs
> +        transform.position = startPosition.transform.position;
Maybe null check here so tests made by others don't need any modifications. For example:
if(startPosition != null) {
    transform.position = startPosition.transform.position;
}

2022-11-01 13:38 UTC, Usmo commented on Assets/Tests/PlayMode/CharacterMovement.cs
> +        GameObject startPosition = new GameObject("Start");
This test file dont need any changes, if player class has null checks implemented as suggested above. :D

2022-11-01 13:39 UTC, Usmo commented on Assets/Scripts/Player.cs
> +            deathScreen.ShowDeathScreen();
Null check also here to check if deathScreen is null.

2022-11-01 13:40 UTC, Usmo commented on Assets/Tests/PlayMode/EnemyTests.cs
> +
This test file dont need any changes, if player class has null checks implemented as suggested above. :D

2022-11-01 13:42 UTC, Usmo requested changes
SampleScene merge problem. Needs to revert all changes to SampleScene -> then rebase to main branch -> then redo deathscreen things to SampleScene

2022-11-06 16:59 UTC, VeikkaH commented
Everything should be fixed, working well, comments noted

2022-11-06 17:02 UTC, Usmo approved these changes

2022-11-06 17:02 UTC, merged